/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'radoslawl' at '9/27/16 3:59 PM' with Gradle 2.14
 *
 * @author radoslawl, @date 9/27/16 3:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
